pipeline {
    agent any

    environment {
        VM_USER       = 'azureuser'
        BUILD_TF      = './build-agent'
        BUCKET        = 'az-app-backend'
        FOLDER_BUCKET = 'build-agent-tf'
        AWS_REGION    = 'us-east-2'
        IMAGE_NAME    = 'michael2209/fullstack-app:latest'
    }

    stages {

        stage('Build Agent Deploy') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                    string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                    string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                    string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID'),
                    string(credentialsId: 'dockerhub-username', variable: 'DOCKER_HUB_USER'),
                    string(credentialsId: 'dockerhub-password', variable: 'DOCKER_HUB_PASS'),
                    string(credentialsId: 'MYSQL_PASSWORD', variable: 'MYSQL_PASSWORD'),
                    string(credentialsId: 'vm-public-ssh-key', variable: 'SSH_PUB'),
                ]) {
                    dir("${env.BUILD_TF}") {
                        sh """
                        terraform init \
                          -backend-config="bucket=${env.BUCKET}" \
                          -backend-config="key=${env.FOLDER_BUCKET}/terraform.tfstate" \
                          -backend-config="region=${env.AWS_REGION}

                        terraform apply -auto-approve \
                          -var "ssh_public_key=${SSH_PUB}" \
                          -var "ARM_CLIENT_ID=${ARM_CLIENT_ID}" \
                          -var "ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}" \
                          -var "ARM_TENANT_ID=${ARM_TENANT_ID}" \
                          -var "ADMIN_PASSWORD=${MYSQL_PASSWORD}" \
                          -var "DOCKER_USER=${DOCKER_HUB_USER}" \
                          -var "DOCKER_PASS=${DOCKER_HUB_PASS}"
                        """
                    }
                }
            }
        }

        stage('Build Agent Destroy') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                    string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                    string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                    string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID'),
                    string(credentialsId: 'dockerhub-username', variable: 'DOCKER_HUB_USER'),
                    string(credentialsId: 'dockerhub-password', variable: 'DOCKER_HUB_PASS'),
                    string(credentialsId: 'MYSQL_PASSWORD', variable: 'MYSQL_PASSWORD'),
                    string(credentialsId: 'vm-public-ssh-key', variable: 'SSH_PUB'),
                ]) {
                    dir("${env.BUILD_TF}") {
                        sh """
                        terraform destroy -auto-approve 
                        """
                    }
                }
            }
        }
    }
}
