pipeline {
    agent any

    environment {
        VM_USER       = 'azureuser'
        BUILD_TF      = './build-agent'
        BUCKET        = 'az-app-backend'
        FOLDER_BUCKET = 'build-agent-tf'
        AWS_REGION    = 'us-east-2'
        IMAGE_NAME    = 'michael2209/fullstack-app:latest'
    }

    stages {

        stage('Terraform Init & Apply') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                    sshUserPrivateKey(credentialsId: 'vm-ssh-private-key', keyFileVariable: 'SSH_KEY_FILE', passphraseVariable: '', usernameVariable: 'SSH_USER')
                ]) {
                    dir("${env.BUILD_TF}") {
                        sh """
                        terraform init \
                          -backend-config="bucket=${BUCKET}" \
                          -backend-config="key=${FOLDER_BUCKET}/terraform.tfstate" \
                          -backend-config="region=${AWS_REGION}"

                        terraform plan -out=myplan.tfplan -input=false \
                          -var="ssh_public_key=$(cat ~/.ssh/id_rsa.pub)" \
                          -var="ssh_private_key=$(cat $SSH_KEY_FILE)"
                        
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }

        stage('Set VM Host') {
            steps {
                script {
                    env.VM_HOST = sh(script: "terraform -chdir=${BUILD_TF} output -raw build_agent_ip", returnStdout: true).trim()
                    echo "VM_HOST=${env.VM_HOST}"
                }
            }
        }

        stage('Fetch Code on VM') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'vm-ssh-private-key', keyFileVariable: 'SSH_KEY_FILE', passphraseVariable: '', usernameVariable: 'VM_USER')]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << 'ENDSSH'
                      set -e
                      if [ ! -d fullstack-app ]; then
                        git clone https://github.com/michaelcriss-dev/fullstack-app.git
                      fi ENDSSH
                    """          
                }
            }
        }

        stage('Lint') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << 'ENDSSH'
                  set -e
                  cd fullstack-app/
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install pylint
                  pylint main.py db.py || true ENDSSH
                """
            }
        }

        stage('Build & Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'dockerhub-password', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')
                ]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << ENDSSH
                      set -e
                      cd fullstack-app/
                      docker build -t ${IMAGE_NAME} .
                      echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin ENDSSH
                    """
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << 'ENDSSH'
                  docker push ${IMAGE_NAME} ENDSSH
                """
            }
        }

        stage('Terraform Destroy') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    dir("${env.BUILD_TF}") {
                        sh """
                        terraform destroy -auto-approve || true
                        """
                    }
                }
            }
        }
    }
}
