pipeline {
    agent any
    environment {
        VM_USER        = 'azureuser'                                     
        SSH_KEY        = credentials('vm-private-ssh-key')  
        SSH_PUBLIC_KEY = credentials('vm-public-ssh-key')
        DEPLOY_TF      = './deploy-agent'
        BUCKET         = 'az-app-backend'
        FOLDER_BUCKET  = 'deploy-agent-tf'
        AWS_REGION     = 'us-east-2'

        APP_RG       = 'FULLSTACK-APP-RG'
        PLAN_NAME    = 'web-plan-service-23432342352'
        LOCATION     = 'Canada Central'
        SKU          = 'B1'
        WEB_APP_NAME = 'fullstack-webapp-2344523423423423'
        DOCKER_IMAGE = 'michael2209/fullstack-app:latest'

        DB_RG          = "FULLSTACK-DB-RG"
        MYSQL_SERVER   = "myflexibleserver${BUILD_NUMBER}"
        ADMIN_USER     = 'mysqladmin'
        ADMIN_PASSWORD = credentials('MYSQL_PASSWORD')
        MYSQL_VERSION  = "8.0.21"
        MYSQL_DB       = "stomology_dep"
        DB_HOST        = "${MYSQL_SERVER}.mysql.database.azure.com"
    }

    stages {

        stage('Build Agent deploy') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                    sshUserPrivateKey(credentialsId: 'vm-ssh-private-key', keyFileVariable: 'SSH_KEY_FILE', passphraseVariable: '', usernameVariable: 'SSH_USER')
                ]) {
                    dir("${env.DEPLOY_TF}") {
                        sh """
                        terraform init \
                          -backend-config="bucket=${BUCKET}" \
                          -backend-config="key=${FOLDER_BUCKET}/terraform.tfstate" \
                          -backend-config="region=${AWS_REGION}"

                        terraform plan -out=myplan.tfplan -input=false \
                          -var="ssh_public_key=${SSH_PUBLIC_KEY}" \
                          -var="ssh_private_key=${SSH_KEY_FILE}"
                        
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }

        stage ('Agent Env'){
            steps{
                script{
                    env.VM_HOST = sh(script: "terraform -chdir=${DEPLOY_TF} output -raw deploy_agent_ip", returnStdout: true).trim()
                    echo "VM_HOST=${env.VM_HOST}"
                }
            }
        }

        stage('Deploying MYSQL-DB') {
            steps {
                script {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << "ENDSSH"
                      set -e
                      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

                      az group create --name ${DB_RG} --location "${LOCATION}"

                      az mysql flexible-server create \\
                        --name ${MYSQL_SERVER} \\
                        --resource-group ${DB_RG} \\
                        --location "${LOCATION}" \\
                        --admin-user ${ADMIN_USER} \\
                        --admin-password ${ADMIN_PASSWORD} \\
                        --sku-name Standard_B1ms \\
                        --version ${MYSQL_VERSION} \\
                        --public-access 0.0.0.0
                    ENDSSH
                    """
                }
            }
        }

        stage('IMPORT DB') {
            steps {
                script {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << "ENDSSH"
                      set -e
                      git clone https://github.com/michaelcriss-dev/fullstack-app.git
                      cd fullstack-app/SQL

                      if ! mysql -h ${DB_HOST} -u ${ADMIN_USER} -p${ADMIN_PASSWORD} -e "USE ${MYSQL_DB};" 2>/dev/null; then
                          echo "Importing DB.."
                          mysql -h ${DB_HOST} -u ${ADMIN_USER} -p${ADMIN_PASSWORD} -e "CREATE DATABASE ${MYSQL_DB};"
                          mysql -h ${DB_HOST} -u ${ADMIN_USER} -p${ADMIN_PASSWORD} ${MYSQL_DB} < ./stomology_dep.sql
                      else
                          echo "Database already exists..."
                      fi
                    ENDSSH
                    """
                }
            }
        }

        stage('Deploying WEB APP') {
            steps {
                script {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_FILE} ${VM_USER}@${VM_HOST} << "ENDSSH"
                      set -e
                      az group create --name ${APP_RG} --location "${LOCATION}"

                      az appservice plan create \\
                        --name ${PLAN_NAME} \\
                        --resource-group ${APP_RG} \\
                        --location "${LOCATION}" \\
                        --is-linux \\
                        --sku ${SKU}

                      az webapp create \\
                        --resource-group ${APP_RG} \\
                        --plan ${PLAN_NAME} \\
                        --name ${WEB_APP_NAME} \\
                        --deployment-container-image-name ${DOCKER_IMAGE}

                      az webapp config appsettings set \\
                        --resource-group ${APP_RG} \\
                        --name ${WEB_APP_NAME} \\
                        --settings \\
                        DB_HOST=${DB_HOST} \\
                        DB_USER=${ADMIN_USER} \\
                        DB_PASSWORD=${ADMIN_PASSWORD}
                    ENDSSH
                    """
                }
            }
        }
        
        stage('Approve'){
            steps{
                script{
                    input message: "Do you want to apply the Terraform changes?", ok: "Yes, Apply"
                }
            }
        }

        stage('Build Agent destroy') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                ]) {
                    dir("${env.DEPLOY_TF}") {
                        sh """
                        terraform destroy -auto-approve
                        """
                    }
                }
            }
        }
    }
}
